sonar.projectKey=oswaldoschermach_speed-violation-service
sonar.organization=oswaldoschermach
sonar.projectName=speed-violation-service
sonar.projectVersion=0.0.1

sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.source=21
sonar.sourceEncoding=UTF-8

sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
sonar.junit.reportPaths=target/surefire-reports,target/failsafe-reports

sonar.coverage.exclusions=**/config/**,**/*Application.java,**/api/request/**,**/api/response/**,**/api/exception/ApiErrorResponse.java
sonar.cpd.exclusions=**/api/request/**,**/api/response/**
