spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT:5432}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: ${DB_POOL_SIZE:10}

server:
  forward-headers-strategy: framework

logging:
  level:
    root: WARN
    com.nebulax.speed_violation_service: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never
      probes:
        enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true

springdoc:
  show-actuator: false

speed-violation:
  openapi:
    public-url: ${APP_PUBLIC_URL:}
